pagination:
  items_per_page: 20
  pages_per_page: 10
  display_mode: pages #pages, results

language: en-en #default language

#if content to admin is multilanguage
languages:
  - es
  - en

persistence:
  ds160_url:
    repository: S3
    parameters:
      folder: ds_160
  pdf_url:
    repository: S3
    parameters:
      folder: voucher
  interview_instructions_file:
    repository: S3
    parameters:
      folder: interview_instructions

models:

#  user:
#    schema:
#      "nice_name": "Usuarios" #name to show on backoffice navigator list
#      public: false #used to show in public (visitors)
#      "by_user": false #if true, logged user id will be added to post data when model is saved on sheet
#    fields:
#      in_list: #fields to show on backoffice list page
#        - email
#        - name
#        - created_at
#      in_detail: #fields to show on detail page
#        - email
#        - name
#        - password
#        - created_at
#      fillable: #campos rellenables, tanto en la creacion como en la edicion
#        - email
#        - name
#        - password
#      fields_schema:
#        email:
#          nice_name: "Correo"
#        name:
#          nice_name: "Nombre del usuario"
#          tooltip: "Qué nombre tiene?"
#          type: "textarea" #type of html field we are going to display
#          classes: "someclass"
#        password:
#          callbacks: #callbacks to be executed when model is saved (list on CallbacksTrait file)
#            - "crypt"
#    "multilanguage_fields":
#      - name
#    related_models: ["note"]

  user:
    schema:
      "nice_name": "Usuarios" #name to show on backoffice navigator list
      public: false #used to show in public (visitors)
      "by_user": false #if true, logged user id will be added to post data when model is saved on sheet
    fields:
      in_list: #fields to show on backoffice list page
        - email
        - name
        - created_at
      in_detail: #fields to show on detail page
        - email
        - name
        - password
        - created_at
      fillable: #campos rellenables, tanto en la creacion como en la edicion
        - email
        - name
        - password
      fields_schema:
        email:
          nice_name: "Correo"
        name:
          nice_name: "Nombre del usuario"
          tooltip: "Qué nombre tiene?"
          type: "textarea" #type of html field we are going to display
          classes: "someclass"
        password:
          callbacks: #callbacks to be executed when model is saved (list on CallbacksTrait file)
            - "crypt"
    "multilanguage_fields":
      - name
#    related_models: ["note"]
