services:

  Session:
    class: Osds\DDDCommon\Infrastructure\Persistence\SessionRepository
    shared: true
    autowire: true

  SmartyView:
    class: Osds\DDDCommon\Infrastructure\View\SmartyView
    public: true
    arguments:
      - "@Twig\\Environment"

  OutputRequest:
    class: Osds\DDDCommon\Infrastructure\Communication\OutputRequest
    public: true
    arguments:
      - "@ServiceAuth"
      - "%env(API_URL)%"

  ServiceAuth:
    class: Osds\Auth\Infrastructure\UI\ServiceAuth
    public: true
    arguments:
      - "@Session"
      - "%env(SERVICE_AUTH_URL)%"
      - "%env(SERVICE_AUTH_USERNAME)%"
      - "%env(SERVICE_AUTH_PASSWORD)%"
      - ""

  UserAuth:
    class: Osds\Auth\Infrastructure\UI\UserAuth
    public: true
    arguments:
      - "@Session"
      - "@OutputRequest"